/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#6a4b70",
        "on-primary-fixed-variant": "#14007b",
        "on-surface-variant": "#596064",
        "primary-dim": "#4843b4",
        "on-secondary-fixed-variant": "#4e5d6f",
        "surface-tint": "#5450c1",
        "surface-variant": "#dce4e8",
        "on-primary-fixed": "#000000",
        "surface": "#f7f9fb",
        "error-container": "#f97386",
        "on-secondary": "#f7f9ff",
        "on-tertiary-container": "#604266",
        "tertiary-fixed-dim": "#e7bfea",
        "inverse-primary": "#8c88fd",
        "on-primary-container": "#0c005c",
        "outline": "#747c80",
        "surface-container-highest": "#dce4e8",
        "surface-bright": "#f7f9fb",
        "on-primary": "#fbf7ff",
        "primary-fixed-dim": "#7f7bef",
        "on-tertiary": "#fff7fb",
        "secondary-fixed-dim": "#c6d6ec",
        "primary": "#5450c1",
        "secondary": "#526073",
        "surface-container-high": "#e3e9ed",
        "tertiary-fixed": "#f5cdf9",
        "error": "#a8364b",
        "tertiary-container": "#f5cdf9",
        "on-error": "#fff7f7",
        "on-tertiary-fixed": "#4c2f52",
        "on-secondary-container": "#445365",
        "inverse-surface": "#0b0f10",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#67486c",
        "outline-variant": "#acb3b7",
        "secondary-container": "#d4e4fa",
        "primary-fixed": "#8c88fd",
        "on-secondary-fixed": "#324052",
        "on-background": "#2c3437",
        "primary-container": "#8c88fd",
        "surface-dim": "#d4dbdf",
        "tertiary": "#745479",
        "background": "#f7f9fb",
        "surface-container": "#eaeff2",
        "inverse-on-surface": "#9a9d9f",
        "secondary-fixed": "#d4e4fa",
        "error-dim": "#6b0221",
        "surface-container-low": "#f0f4f7",
        "on-surface": "#2c3437",
        "on-error-container": "#6e0523",
        "secondary-dim": "#465467"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
